runtime: go
api_version: go1

service: mars

handlers:
- url: /update
  script: _go_app
  login: admin
- url: /.*
  script: _go_app

env_variables:
  # Replace INSTANCE_CONNECTION_NAME with the value obtained when configuring your
  # Cloud SQL instance, available from the Google Cloud Console or from the Cloud SDK.
  # For Cloud SQL 2nd generation instances, this should be in the form of "project:region:instance".
  #
  SQL_CONNECTION_PROTO: cloudsql
  CLOUDSQL_CONNECTION_NAME: disla-goog-com-csa-ext:us-central1:mars-images
  # SQL_CONNECTION_PROTO: tcp
  # CLOUDSQL_CONNECTION_NAME: 127.0.0.1:3306
  #
  # Replace username and password if you aren't using the root user.
  CLOUDSQL_USER: mars
  CLOUDSQL_PASSWORD: ''
  IMAGE_DATABASE: mars-images